baseURL = "https://fevemania.github.io/"
title = "fevemania's blog"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

[params]
  description = "Minimalist theme for Hugo"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "MunifTanjim"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  Author = "fevemania"
  disqusShortname = "fevemania-github-io"

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "fevemania"

[author.social]
  # codepen = "MunifTanjim"
  facebook = "fevemania"
  github = "fevemania/fevemania-hugo"
  # instagram = "instagram"
  # twitter = "MunifTanjim"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = -70
#   identifier = "repository"
  url = "https://fevemania.github.io/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
